{
  'plugins':
    [
      [
        '@semantic-release/commit-analyzer',
        {
          'releaseRules':
            [
              { 'type': 'docs', 'release': 'patch' },
              { 'type': 'refactor', 'release': 'patch' },
              { 'type': 'style', 'release': 'patch' },
            ],
        },
      ],
      '@semantic-release/release-notes-generator',
      '@semantic-release/changelog',
      '@semantic-release/npm',
      '@semantic-release/github',
      [
        '@semantic-release/git',
        {
          'assets': ['CHANGELOG.md', 'package.json'],
          'message': "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        },
      ],
    ],
  'branches':
    [
      '+([0-9])?(.{+([0-9]),x}).x',
      'main',
      'next',
      'next-major',
      { name: 'beta', prerelease: true },
      { name: 'alpha', prerelease: true },
    ],
}
