name: PR

on: [pull_request]

jobs:
  install-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          npm install
          npm install react
      - name: Build package
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Prepare new release
        run: npm run release -- --dry-run
