name: PR

on: [pull_request]

jobs:
  install-build-and-test:
    name: Install, build and test PR
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build package
        run: pnpm build
      - name: Run linting
        run: pnpm lint
      - name: Run tests
        run: pnpm test-ci
      - name: Run typecheck
        run: pnpm typecheck
      - name: Code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: pnpm codecov
      - name: Prepare new release
        run: pnpm semantic-release --dry-run
