name: Close Stale Issues and Pull Requests

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

permissions:
  issues: write
  pull-requests: write

jobs:
  close_stale_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@4391f3da665fdf50b6810c1a66712fb9ba21aa93 # v11.0.0
